# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='file_five',
        ),
        migrations.RemoveField(
            model_name='new',
            name='file_four',
        ),
        migrations.RemoveField(
            model_name='new',
            name='file_six',
        ),
        migrations.RemoveField(
            model_name='new',
            name='file_three',
        ),
        migrations.RemoveField(
            model_name='new',
            name='file_two',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h2_paragraph1',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h2_paragraph2',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h2_paragraph3',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h3_paragraph1',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h3_paragraph2',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h3_paragraph3',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h4_paragraph1',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h4_paragraph2',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h4_paragraph3',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h5_paragraph1',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h5_paragraph2',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h5_paragraph3',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h6_paragraph1',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h6_paragraph2',
        ),
        migrations.RemoveField(
            model_name='new',
            name='h6_paragraph3',
        ),
        migrations.RemoveField(
            model_name='new',
            name='heading_five',
        ),
        migrations.RemoveField(
            model_name='new',
            name='heading_four',
        ),
        migrations.RemoveField(
            model_name='new',
            name='heading_six',
        ),
        migrations.RemoveField(
            model_name='new',
            name='heading_three',
        ),
        migrations.RemoveField(
            model_name='new',
            name='heading_two',
        ),
        migrations.RemoveField(
            model_name='new',
            name='image_five',
        ),
        migrations.RemoveField(
            model_name='new',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='new',
            name='image_six',
        ),
        migrations.RemoveField(
            model_name='new',
            name='image_three',
        ),
        migrations.AlterField(
            model_name='new',
            name='image_one',
            field=models.ImageField(blank=True, upload_to='news/news_photos'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image_two',
            field=models.ImageField(blank=True, upload_to='news/news_photos'),
        ),
    ]
