# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170103_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='image_two',
        ),
        migrations.AddField(
            model_name='new',
            name='h1_paragraph4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h1_paragraph5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h2_paragraph1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h2_paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h2_paragraph3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h2_paragraph4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h2_paragraph5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h3_paragraph1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h3_paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h3_paragraph3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h3_paragraph4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='h3_paragraph5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='new',
            name='heading_three',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='new',
            name='heading_two',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
